### ISSUE TITLE
如果做部分同构直出呢？

### ISSUE THREAD

**Issue by cbbfcd** [yangfan0095/react-koa2-ssr#11]
我觉得这个架子很棒，有关于部分同构直出的方案吗？希望一部分静态页面直出，部分还是前端渲染，只是通过中间层加装数据后直出给它。

**Comment by yangfan0095** [comment]
这个项目目前还是趋于研究性质的， 用于探究React  服务端渲染。
本质上node服务对api 进行了路由划分 ，目前所有路由除了静态资源都默认是和前端SPA一一对应的。
要实现你的需求 ，只需要对 node 层的路由进行再次划分 ， 写个方法判断静态资源路由绕开 和SPA 的同构，就可以实现起一个服务 同时渲染静态页面和SPA 同构

**Comment by cbbfcd** [comment]
谢谢 大概有思路了
