### ISSUE TITLE
koa2的话能够做到不用重启，每次客户端都build不是很麻烦吗？请问有什么办法能够解决这种问题

### ISSUE THREAD

**Issue by blockmood** [yangfan0095/react-koa2-ssr#12]

**Comment by yangfan0095** [comment]
首先 你看到前端代码每次build ,是因为那是开发环境，每次部署都会给前端代码打包。F5刷新的时候 走的是静态资源。返回打包好的文件，开发环境，直接用的create-react-app那一套 ，直接热替换。 如果是线上环境部署不存在这个问题。

**Comment by blockmood** [comment]
我就是不太明白这点，麻烦出个demo吧，谢了。
